### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by jeksterslab** [ielbadisy/missCforest#1]
I am getting warnings using this example. What do these warnings mean?

> data("airquality")
> airquality_subset <- airquality[ , 1:4]
> ximp <- missCforest::missCforest(airquality_subset, .~.)

There were 50 or more warnings (use warnings() to see the first 50)

> warnings()

Warning messages:
1: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
2: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
3: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
4: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
5: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
6: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
7: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
8: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
9: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
10: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
11: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
12: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
13: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
14: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
15: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
16: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
17: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
18: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
19: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
20: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
21: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
22: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
23: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
24: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
25: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
26: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
27: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
28: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
29: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
30: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
31: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
32: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
33: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
34: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
35: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
36: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
37: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
38: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
39: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
40: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
41: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
42: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
43: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
44: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
45: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
46: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
47: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
48: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
49: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length
50: In retid[indx] <- fitted_node(kids_node(node)[[i]], data,  ... :
  number of items to replace is not a multiple of replacement length

**Comment by ielbadisy** [comment]
Hi @jeksterslab, 

Thank you for reporting this issue. 

This warning most likely comes from `partykit::fitted_node()` which "...performs all splits recursively and returns the identifier id of the terminal node each observation in data[obs,] belongs to".  Something related to Cforest procedure for building trees.  

But what is more intriguing is that this message only appears when the dataset in hand contains variables without NA (i.e. completely observed). 

Using your example, I forced all variables to contain missing values and the warning no longer appears : 

```
data("airquality")
airquality_subset <- missCforest::generateNA(airquality, 0.2)
ximp <- missCforest::missCforest(airquality_subset, .~.)
```
